// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Account struct {
	AccountID     int32
	UserID        uuid.NullUUID
	AccountNumber string
	AccountType   string
	Balance       string
	DateOpened    sql.NullTime
}

type Transaction struct {
	TransactionID int32
	AccountID     sql.NullInt32
	RecepientID   sql.NullInt32
	Amount        string
	Type          string
	Timestamp     sql.NullTime
}

type User struct {
	UserID       uuid.UUID
	Username     string
	PasswordHash string
	Email        string
	FullName     string
	DateJoined   sql.NullTime
}
