// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: transaction.sql

package database

import (
	"context"
	"database/sql"
)

const saveTransaction = `-- name: SaveTransaction :one
INSERT INTO
  transactions (account_id, recepient_id, type)
VALUES
  ($1, $2, $3) RETURNING transaction_id, account_id, recepient_id, type, timestamp
`

type SaveTransactionParams struct {
	AccountID   sql.NullInt32
	RecepientID sql.NullInt32
	Type        string
}

func (q *Queries) SaveTransaction(ctx context.Context, arg SaveTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, saveTransaction, arg.AccountID, arg.RecepientID, arg.Type)
	var i Transaction
	err := row.Scan(
		&i.TransactionID,
		&i.AccountID,
		&i.RecepientID,
		&i.Type,
		&i.Timestamp,
	)
	return i, err
}
