// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: transaction.sql

package database

import (
	"context"
	"database/sql"
)

const saveTransaction = `-- name: SaveTransaction :exec
INSERT INTO
  transactions (account_id, recepient_id,amount, type)
VALUES
  ($1, $2, $3 ,$4) RETURNING transaction_id, account_id, recepient_id, amount, type, timestamp
`

type SaveTransactionParams struct {
	AccountID   sql.NullInt32
	RecepientID sql.NullInt32
	Amount      string
	Type        string
}

func (q *Queries) SaveTransaction(ctx context.Context, arg SaveTransactionParams) error {
	_, err := q.db.ExecContext(ctx, saveTransaction,
		arg.AccountID,
		arg.RecepientID,
		arg.Amount,
		arg.Type,
	)
	return err
}
