version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://postgres:YMNCgcDIXGFFjTCPBHssUFfXxajttktM@monorail.proxy.rlwy.net:45813/railway
      SECRET_KEY: "secret"
    depends_on:
      - postgres
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YMNCgcDIXGFFjTCPBHssUFfXxajttktM
      POSTGRES_DB: railway
    ports:
      - "5432:5432"
    volumes: 
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
